### PR TITLE
Allow nameserver's create view to create glue for delegated zones

### PR DESCRIPTION
**Pull request by murrown**

### CODE REVIEW

**Comment by akeym** [comment]
Attempting to create an NS for ceoas.oregonstate.edu with glue dnsman.oce.orst.edu 128.193.64.33 silently fails. ceoas.oregonstate.edu is in a container, zone.delegations, which is also where I specified to place the glue.

**Comment by akeym** [comment]
It appears that the validation error just didn't display.  The domain wasn't set as delegated.

**Comment by murrown** [comment]
It shouldn't fail silently, so I'll try to fix that... but after marking the domain as delegated, it worked as expected?

**Comment by akeym** [comment]
It seems like it, but when I go back to edit the NS record, the glue information is gone, and the Glue column of the NS list says 'None.'

**Comment by akeym** [comment]
It did create an A record called dnsman.ceoas.oregonstate.edu... which isn't valid but for a different reason: I shouldn't be creating glue here because the NS is in a different zone, not ceoas.oregonstate.edu

**Comment by murrown** [comment]
Regarding the invalid address record you created, that should no longer be possible. The reason you were able to create it is because the Nameserver form will override that validation when creating glue for a new Nameserver.

**Comment by akeym** [comment]
I approve - if you're done, merge

**Pull request merged**
