### PR TITLE
Fix fail_mail

### PR DESCRIPTION
**Pull request by drkitty**
**Resolves issue #472.**

### CODE REVIEW

**Comment by akeym** [comment]
looks like you forgot to put FAIL_EMAIL_FROM in the travis test settings py

**Comment by drkitty** [comment]
gah

**Comment by drkitty** [comment]
Sorry about that. I keep forgetting about tests.

**Comment by akeym** [comment]
I can't seem to trigger fail_mail.  I've tried pushing to a non existent repo, one without the proper directory ("zones" for DNS), and even hit the line limit: cyder.base.vcs.SanityCheckFailure: Line count increase (145776) exceeded limit (1).

my settings:

# sender
FAIL_EMAIL_FROM = 'root@cyder-dev.nws.oregonstate.edu'

# recipients
FAIL_EMAIL_TO = (
    'mike.akey@oregonstate.edu',
)

# the SMTP server to send email via
FAIL_EMAIL_SERVER = 'localhost'

**Comment by akeym** [comment]
Guess the proper use of fail_mail was never actually implemented.. so I guess this does what its supposed to now, and there's a new issue to deal with missing functionality.

**Comment by murrown** [comment]
The aforementioned issue: https://github.com/OSU-Net/cyder/issues/980

**Pull request merged**
