### PR TITLE
Validate container permissions for static interface-range relationships

### PR DESCRIPTION
**Pull request by murrown**
Resolves https://github.com/OSU-Net/cyder/issues/982

### CODE REVIEW

**Comment by murrown** [comment]
It's worth noting that if a range is removed from a container, the interfaces in that range won't be re-validated. But no one will be able to update them until they are put in an appropriate range/container.

**Comment by drkitty** [comment]
According to @akeym, a static interface should be allowed not to be inside a static range.

**Comment by drkitty** [comment]
It's very important that every object can be successfully re-saved without modifications—a user shouldn't be able to break things for other users in such a non-obvious way. Re-validating interfaces that are no longer allowed in a range is definitely the way to go, even if it's expensive.

**Comment by akeym** [comment]
This edge case is a fun one.. we shouldn't allow static interfaces to exist that use IPs that we don't have networks for... but not having a range is okay - e.g. router interface on a subnet is 128.193.128.1 and the range is 128.193.128.2-127.  I think we allow this if dhcp is disabled currently?

**Comment by murrown** [comment]
@drkitty This circumstance is a bit different. It's not a matter of the form loading incorrectly, so submitting it immediately creates errors; rather, the object simply can't be updated unless the user chooses a correct container for it.

This issue wasn't introduced by this pull request, either. I think that removing a domain from a container has the same effect on various records that have containers which must match their domain's container. It's annoying, for sure; but I can't imagine any scenarios that would make fixing it a priority.

**Comment by murrown** [comment]
If this state of affairs is really unacceptable, then I think these are the only real solutions...

1. Delete all of the interfaces in range R when R is removed from container X.
2. Delete all of the interfaces in range R that are in container X when R is removed from X. (a bit ambiguous)
3. Reassign all of the interfaces in range R that are in container X to another one of R's containers when R is removed from X (not always possible, ambiguous)
4. Don't allow R to be removed from container X if there are interfaces in R that are in container X.

Implementing any one of these is going to be a bit tedious, but I'm pretty sure it can be done.

**Comment by akeym** [comment]
option four is acceptable to me.  Should this be done in a different PR/issue?

**Comment by murrown** [comment]
Yeah, since it's an issue independent of this pull request. I've created a new issue for it at https://github.com/OSU-Net/cyder/issues/987.

**Comment by akeym** [comment]
Well, I suppose this one is ready

**Pull request merged**
