### PR TITLE
Add supernets

### PR DESCRIPTION
**Pull request by murrown**
Must resolve https://github.com/OSU-Net/cyder/issues/977
*Requires a schema migration*

### CODE REVIEW

**Comment by murrown** [comment]
Oh, yeah, I forgot to mention about the schema migration. After changing the Network model, every network objects needs to have `update_network` run to recalculate its IP addresses from the network string. I'll include this in the data migration when it comes time to merge this, but for testing, please run this script:
```python
for n in network.objects.all():
    n.update_network()
    n.save()
```

**Comment by akeym** [comment]
@murrown what was the reasoning behind not using the prefixlen any more?

**Comment by drkitty** [comment]
@akeym: It makes it simpler to ensure networks don't span supernets.

**Comment by murrown** [comment]
Yeah, what @drkitty said, among other things. It's difficult to use prefixlen in a database query to retrieve all of the subnets in a given supernet. At least, I couldn't think of an easy way, but maybe I'm just dumb.

**Comment by akeym** [comment]
Couple things:  

The description field should be a text area, not just a single line.

Superblock should be listed on the Network detail view if that Network is in a Superblock (a link to the superblock detail view)

**Comment by murrown** [comment]
I added the necessary schema migrations

**Comment by murrown** [comment]
I think I'll just merge this since it was already looked at a couple of times and I'm pretty confident after getting those schema migrations to work.

**Pull request merged**
