### PR TITLE
Autocreate routers option

### PR DESCRIPTION
**Pull request by murrown**
Solution for https://github.com/OSU-Net/cyder/issues/1015

### CODE REVIEW

**Comment by murrown** [comment]
It's a bit clunky and there's no autocomplete feature but it's the best I can do without tinkering with javascript, which would take a significant amount of time.

**Comment by akeym** [comment]
Can we make that auto-generate checkbox set by default?

**Comment by murrown** [comment]
Sure

**Comment by akeym** [comment]
Actually, after talking with the NOC guys - they want to make this idiot proof.  They want the form to prevent you from entering a gateway outside the network in the network string.  And the subnet mask should not be allowed to be smaller than the size of the network.

Its possible we may just want to remove the form fields all together, and if they don't want the defaults, they can change it later.. how do you feel about the requirements I mentioned above?

**Comment by murrown** [comment]
It wouldn't be difficult to validate the inputed fields. I can probably whip that out before I go home.

**Comment by murrown** [comment]
That should do it

**Pull request merged**
