### PR TITLE
Do not hide ctnr field if browser is ie

### PR DESCRIPTION
**Pull request by church29**
Very strange behaviour in ie. Seems to be some compatibility issues with django.
Not a fix, just a workaround for https://github.com/OSU-Net/cyder/issues/877

### CODE REVIEW

**Comment by drkitty** [comment]
This doesn't fix the network edit form on a network detail page.

**Comment by drkitty** [comment]
Doesn't appear to fix the dynamic interface creation form on a system detail page, either.

**Comment by drkitty** [comment]
Apparently the container field isn't being shown on the dynamic interface edit form like it's supposed to. I'm not really sure what's going on.

**Comment by drkitty** [comment]
Looks like the `ctnr` field already gets a `HiddenInput` widget in `cyder/base/views.py:386`.

**Comment by church29** [comment]
Replaced by https://github.com/OSU-Net/cyder/pull/954

**Pull request closed without merging**
