### PR TITLE
Show dns statistics in global

### PR DESCRIPTION
**Pull request by church29**
Solves https://github.com/OSU-Net/cyder/issues/896

### CODE REVIEW

**Comment by akeym** [comment]
@church29 i'm not sure what I'm supposed to be seeing here.  Global still shows all zeros.

**Comment by church29** [comment]
Interesting. It seemed to be working on my instance, but I did rush this a bit.

**Comment by drkitty** [comment]
Works for me, at least for SOAs, NSes, domains, and reverse domains. (I'll test the rest when Maintain migration finishes.)

**Comment by drkitty** [comment]
Now it just shows the global stats regardless of what the active container is.

**Comment by church29** [comment]
Dumb copy pasta mistakes.

**Pull request merged**
