### PR TITLE
Allow the server and domain name to be the same for nameserver records

### PR DESCRIPTION
**Pull request by murrown**
Resolves https://github.com/OSU-Net/cyder/issues/943

### CODE REVIEW

**Comment by akeym** [comment]
Hmm, when I created the glue it seemed to not put it in the public or private view by default.. are you seeing this?

**Comment by murrown** [comment]
Ah, yeah. Guess I forgot to do that.

**Comment by murrown** [comment]
Isn't it a problem if the Nameserver record is in different views than its glue, in the first place? What if someone removes a glue record from the public and private views without knowing that it's a glue record?

**Comment by murrown** [comment]
The update I added assigns glue to all views by default, but I didn't make any kind of validation to prevent glue from being removed from any views. I don't know if we need it.

**Comment by akeym** [comment]
In theory the glue must be in all views that the corresponding NS record is in.

**Comment by akeym** [comment]
Not sure I care to fix that at this point...

**Pull request merged**
