### PR TITLE
Show Obj's ctnr in detail view

### PR DESCRIPTION
**Pull request by church29**
Resolves https://github.com/OSU-Net/cyder/issues/936

### CODE REVIEW

**Comment by murrown** [comment]
Is there any danger of this attempting to show containers for objects that do not have a container? It doesn't look like it makes any checks to determine if the object actually has a container.

**Comment by church29** [comment]
+        if detail_view and objects and hasattr(objects[0], 'ctnr'):
+            self.show_ctnr = True
+        else:
+            self.show_ctnr = False

**Comment by murrown** [comment]
Don't know how I missed that. Looks good to me.

**Comment by drkitty** [comment]
Out of curiosity, how does this solution compare to adding a container tuple in each model's `detail()` method? I'm kind of worried about how procedural (i.e., anti-OO) our presentation code is becoming.

**Comment by drkitty** [comment]
Alright, I guess we don't want containers in list views, so it would require a new method, like `detail_detail()` or something.

**Comment by murrown** [comment]
Yeah, normally I'd rather do as @drkitty suggested but that was the issue.

**Pull request merged**
