### PR TITLE
Really truly fix static interface and address record conflict validation

### PR DESCRIPTION
**Pull request by murrown**
Fixes mistakes in https://github.com/OSU-Net/cyder/pull/1027.

```irc
12:54 <@murrown> ARs: unique by (fqdn, ip_str)
12:55 <@murrown> SIs: unique by fqdn and ip_str
12:55 <@murrown> SIs w/ ARs: unique by fqdn, but can share IPs
```

### CODE REVIEW

**Comment by akeym** [comment]
It looks like a AAAA and an SI with the same name conflict.. haven't found out if its just this branch or on master as well, but in either case this is the place to fix it.  example: time.oregonstate.edu

**Comment by murrown** [comment]
So AAAA records should be treated differently? Presumably so we can have an interface with an ipv4 and an ipv6 address? Suppose the interface was created with an ipv6 address. In that situation, we shouldn't allow a AAAA record with the same name, but we should allow an A record with the same name?

I'm guessing we don't want to allow multiple AAAA records with a conflicting name either. So having a static interface called time.oregonstate.edu, and also four different AAAA records called time.oregonstate.edu, is that a bad idea?

**Comment by akeym** [comment]
The same rules apply if its an ipv6 interface and a AAAA record.  More importantly, AAAA is not A.  We group them together, but they are distinct types of records, and an A and a AAAA of the same name do not constitute a round-robin.

**Comment by murrown** [comment]
So treat AAAA records with the same validation as A records, but make AAAA records and A records agnostic toward each other?

**Comment by akeym** [comment]
sounds like you understand

**Comment by akeym** [comment]
So, the example 'time.oregonstate.edu' still conflicts because it shares the name between a static interface and an A record.  Name checking/round-robin checking should also take in to account different ip type (A vs AAAA).

**Comment by murrown** [comment]
Whoops. Sorry, there was a separate code block for static/ar conflicts. I'll get a fix out as soon as I can figure out the tests.

**Comment by murrown** [comment]
Alright, should be good now.

**Pull request merged**
