### PR TITLE
Front page links

### PR DESCRIPTION
**Pull request by church29**
Solves https://github.com/OSU-Net/cyder/issues/834

### CODE REVIEW

**Comment by akeym** [comment]
@church29 can't remember from the meeting, but were you going to change the "register a new device" link to go directly to the create form?

**Comment by church29** [comment]
I was going to, but you mentioned users should know where to go to do these things, so I had it redirect to the system list view. I can change if needed though.

**Comment by akeym** [comment]
Yeah, I'm going to go back on that.. lets just make it easy for them.  How
about you put (Create a System) after the existing text so they at least
know what the heck they're doing.

**Comment by drkitty** [comment]
**Superseded by PR #879.**

**Pull request merged**
