### PR TITLE
Verify and fix permissions

### PR DESCRIPTION
**Pull request by drkitty**
**Resolves issue #769.**

### CODE REVIEW

**Comment by drkitty** [comment]
Perhaps I misinterpreted the spec. Let me check the email.

**Comment by drkitty** [comment]
Nope, the email is just as spartan. @akeym: Could you clarify what's meant by "RW" in the permissions spec you emailed us in December? Does it include creation and deletion, or just updating?

**Comment by akeym** [comment]
read write implies any read or write operation

**Comment by murrown** [comment]
Since that's cleared up, this is ready for merge.

**Pull request merged**
