### PR TITLE
Send email and create a stop file on build failure

### PR DESCRIPTION
**Pull request by drkitty**
**Resolves issue #980.**

### CODE REVIEW

**Comment by akeym** [comment]
Unfortunately the tests will likely always fail because it can't send mail...

**Comment by akeym** [comment]
@drkitty  This seems fine to me now.  Should I wait to merge and let you make test changes or just merge?

**Comment by drkitty** [comment]
Uh, I'll look at tests. I'd like to avoid having failing tests on master.

**Comment by drkitty** [comment]
Fixed!

**Pull request merged**
