### PR TITLE
Show all ctnr fields

### PR DESCRIPTION
**Pull request by church29**
This is a re-submission of https://github.com/OSU-Net/cyder/pull/954

### CODE REVIEW

**Comment by akeym** [comment]
I get this error when trying to change the container:

Cannot change container; interface's container and system's container must be the same. Please change the system's container instead.

Also, the container list isn't sorted.

**Comment by murrown** [comment]
It's not allowing containers to change because of a backend issue... I'm considering whether it's worth it write a workaround, or if I should go ahead and remove containers from interfaces, already.

**Comment by church29** [comment]
@akeym That is a separate issue and not one this pull request was made to handle. @murrown I think removing them altogether is the best choice. A lot of tests will need fixing though.

**Comment by akeym** [comment]
Alright, but I don't want this merged until that is fixed.. can be a different PR. I don't want to confuse our users by putting in an extra field that doesn't work.

**Comment by church29** [comment]
@murrown I fixed the issue. The interface ctnr updating was occurring before the system was actually saved.This will have to do until ctnrs are removed from interfaces entirely.

**Comment by murrown** [comment]
Superseded by https://github.com/OSU-Net/cyder/issues/979

**Pull request closed without merging**
