### PR TITLE
Preserve DNS record domain name case

### PR DESCRIPTION
**Pull request by drkitty**

### CODE REVIEW

**Comment by drkitty** [comment]
Waiting for my migration to finish so I can run a comparison.

**Comment by murrown** [comment]
In addition to migrations, at least one `lower()` call needs to be removed from builds as well. Use the config files generated by Cyder to verify that case is retained.

**Comment by drkitty** [comment]
Thought I got them all. I'll look again.

**Comment by drkitty** [comment]
I don't see any other important calls to `lower()`. There's one in a sort key lambda expression, but that doesn't matter.

**Comment by murrown** [comment]
Yeah, looks like I was wrong.

**Comment by drkitty** [comment]
Didn't get around to running a comparison. Doing that now. Will report back when it's done.

**Comment by murrown** [comment]
Resolves https://github.com/OSU-Net/cyder/issues/876

**Comment by murrown** [comment]
I ran a migration and looked at builds and this seems to be okay. How did your comparison go?

**Comment by murrown** [comment]
Leaving this open for now because merging it will break DHCP comparison. Otherwise it looks good though.

**Comment by drkitty** [comment]
Looks good.

**Pull request merged**
