### PR TITLE
Visually distinguish development and production instances

### PR DESCRIPTION
**Pull request by drkitty**
**Resolves issue #959.**

This pull request makes the header bar orange instead of black when the `DEV` setting is True.

### CODE REVIEW

**Comment by akeym** [comment]
I've set 
```DEV = True
DEBUG = True
TEMPLATE_DEBUG = DEBUG```
and it still shows up black to me on cyder-dev

**Comment by drkitty** [comment]
Did you restart the server? Is jingo-minify configured strangely on your installation?

**Comment by akeym** [comment]
Yes, I did.  It did its standard thing of not loading CSS on the first try because the new css files haven't been built yet.. I don't know what you mean by "configured strangely" nor do I even know how to configure anything about jingo-minify...  You may look at the configuration on cyder-dev if you'd like to see how I'm set up.

**Comment by drkitty** [comment]
I'll check again.

**Comment by drkitty** [comment]
Note to self: Looks like I didn't test the homepage. It uses a different, simpler view that doesn't pass the `dev` variable to the template. We ***really*** need to sort out this view mess.

**Comment by drkitty** [comment]
This is ready for a second review.

**Pull request merged**
