### PR TITLE
Create an audit log for objects

### LINKED ISSUE #690: Object audit log
All DNS and DHCP related objects should have audit history (e.g. a changelog).  This should include:
- The user who made the change and a copy of the previous state of the Object
- The ability to revert a change (Restore to a previous state)
- The number of previous states to store for an object must be configurable

Additionally - objects should show the last time an object was edited, and the user who edited it, in the UI.  Can be limted to an object's detail view.

Just wanted to start the planning/design phase on this feature - DNS-container privs should be considered priority over this.

### PR DESCRIPTION
**Pull request by zeeman**
This branch should be mostly complete by now. I'm working on some minor changes to improve the readability of the logs, mainly in cases where the name of an attribute differs significantly from the label shown in the UI. There are also some weird potential bugs that I'm trying to sort out.

This is the current output of every serializer used for logging. Any thoughts on field names or representations?
```
DynamicInterface
{
    "container": "zone.public",
    "workgroup": "Default",
    "system": "public-d92fdd178fd58b48a4756d2661246c71-Wireless",
    "mac": "00:22:fb:43:de:50",
    "range": "Wireless registration 10.255.255.255-10.255.255.255 (186)",
    "dhcp_enabled": true,
    "expire": null,
    "last_save_user": null
}

StaticInterface
{
    "container": "zone.nacse.org",
    "mac": "00:c0:b7:97:c0:a6",
    "reverse_domain": "193.10.in-addr.arpa",
    "system": "kec1108a-ap7801-r11-2",
    "workgroup": "Default",
    "dhcp_enabled": true,
    "dns_enabled": true,
    "ip": "10.193.50.62",
    "last_save_user": null,
    "description": "",
    "expire": null
}

Network
{
    "vlan": "IS:VideoNET",
    "site": "Campus",
    "vrf": "Legacy",
    "ip_type": "4",
    "network_address": "128.193.11.0/26",
    "enabled": true,
    "dhcp_config_extras": "",
    "last_save_user": null
}

Range
{
    "name": "",
    "network": "128.193.0.0/27",
    "range_type": "static",
    "ip_type": "4",
    "start_address": "128.193.0.4",
    "end_address": "128.193.0.31",
    "domain": "nws.oregonstate.edu",
    "is_reserved": false,
    "allow": "l",
    "dhcpd_raw_include": "",
    "dhcp_enabled": true,
    "description": "",
    "allow_voip_phones": true,
    "last_save_user": null
}

Vlan
{
    "name": "COB-SBNT76",
    "number": 76,
    "last_save_user": null
}

AddressRecord
{
    "label": "",
    "domain": "itnsecure.orvsd.org",
    "ip_address": "128.193.4.38",
    "last_save_user": "test_superuser",
    "ttl": 3601,
    "description": "Testing."
}

CNAME
{
    "label": "www",
    "domain": "emt.orst.edu",
    "target": "www.orst.edu",
    "last_save_user": null,
    "description": "",
    "ttl": 3600
}

Domain
{
    "name": "arpa",
    "master_domain": null,
    "soa": "None",
    "is_reverse": true,
    "dirty": false,
    "purgeable": false,
    "delegated": false,
    "last_save_user": null
}

MX
{
    "label": "",
    "domain": "nacse.org",
    "server": "relay.oregonstate.edu",
    "priority": 5,
    "ttl": 86400,
    "description": "",
    "last_save_user": "test_superuser"
}

Nameserver
{
    "domain": "10.in-addr.arpa",
    "server": "ns1.oregonstate.edu",
    "ttl": 3600,
    "last_save_user": null,
    "description": ""
}

PTR
{
    "ip_address": "199.201.139.9",
    "fqdn": "corv-car1-gw.nero.net",
    "ttl": 3600,
    "last_save_user": null
}

SOA
{
    "root_domain": "10.in-addr.arpa",
    "primary": "ns1.oregonstate.edu",
    "contact": "hostmaster.oregonstate.edu",
    "expire": 1209600,
    "retry": 86400,
    "refresh": 180,
    "minimum": 180,
    "ttl": 3600,
    "description": "",
    "is_signed": false,
    "dns_enabled": true,
    "last_save_user": null
}

SRV
{
    "label": "_test2",
    "domain": "2wow.oregonstate.edu",
    "target": "testing",
    "port": 8420,
    "priority": 2,
    "weight": 2,
    "ttl": 3600,
    "description": "Hi!",
    "ctnr": "zone.baf",
    "last_save_user": "test_superuser"
}

SSHFP
{
    "label": "test_sshfp",
    "domain": 493,
    "key": "5bf1ad927dfb8679496a2e6cf00cbe50c1c87145",
    "algorithm_number": 1,
    "fingerprint_type": 1,
    "ttl": 3611,
    "description": "Junk SSHFP for testing",
    "ctnr": "zone.baf",
    "last_save_user": "test_superuser"
}

TXT
{
    "label": "test_txt",
    "domain": "2wow.oregonstate.edu",
    "txt_data": "test data",
    "ttl": 3600,
    "description": "?",
    "ctnr": 10,
    "last_save_user": "test_superuser"
}
```

Resolves #690.

### CODE REVIEW

**Comment by drkitty** [comment]
*bump*

**Comment by drkitty** [comment]
Put `MAX_LOG_ENTRIES` in `cyder/settings/local.py`.

**Comment by drkitty** [comment]
Please fix errors caused by botched merge.

**Comment by drkitty** [comment]
Hmm. Actually not sure what's going on. Definitely errors.

**Comment by drkitty** [comment]
Your last merge somehow left an import of a function that was removed. I don't think it was your fault, but make sure to run tests every time you merge from master—things get messed up quite often.

**Comment by drkitty** [comment]
I created, edited, and then attempted to delete a TXT record. It failed on line 88 of `cyder/base/models.py`:

`log=self.log + "\n" + self.serialized(),`

The exception value is "serialized() takes exactly 2 arguments (1 given)".

**Comment by zeeman** [comment]
I have been working on resolving these issues and have a planned fix for the serialized() bug.

**Comment by drkitty** [comment]
Also, don't bother with Travis. We should get our own build box set up, but that can wait until after deployment.

**Comment by drkitty** [comment]
Tests pass. Is this ready?

**Comment by akeym** [comment]
ImportError: cannot import name MAX_LOG_ENTRIES

**Comment by akeym** [comment]
Where is log data actually stored - deletelog table?  I've edited a static interface and don't see anything there, or in the log column on static_interface.  I do see a last_save_user_id, but its wrong (maybe just migrated from Maintain?)

**Comment by akeym** [comment]
Ok, I see a log entry for Range, but it isn't in the UI.

Also, why is the last_save_user part of the json blob rather than a separate column?

**Comment by zeeman** [comment]
So it turns out my most recent merge deleted a very important line in the base template. Now you should be able to see the audit log in the UI.

**Comment by akeym** [comment]
this doesn't log attr changes right?

**Comment by jwasinger** [comment]
I'm going through UI tests on Chrome.  One issue that I've found is this:
when adding a Domain/Range/Workgroup to a container that doesn't exist, no error is shown.  However, the server log shows an HTTP 500 error.

**Comment by drkitty** [comment]
@jwasinger: How can you specify a container that doesn't exist?

**Comment by jwasinger** [comment]
That was poorly worded on my part.  It's the Domain/Range/Workgroup that doesn't exist while the container does.

**Comment by drkitty** [comment]
I think this was brought up during the most recent meeting. I don't remember what we decided.

**Comment by akeym** [comment]
what happened to the review of this?  where is this at?

**Comment by drkitty** [comment]
Nobody followed up on the issue discovered by @jwasinger, although I think it's present on master as well.

**Comment by drkitty** [comment]
**Superseded by PR #944.**

**Pull request closed without merging**
