### PR TITLE
Form submit keypress logic

### PR DESCRIPTION
**Pull request by church29**
Resolves: https://github.com/OSU-Net/cyder/issues/846

### CODE REVIEW

**Comment by church29** [comment]
@drkitty I would like to go over this with you.

**Comment by drkitty** [comment]
Submitting the workgroup creation form with the enter key still causes a CSRF failure.

**Comment by drkitty** [comment]
I'm actually not sure this prevents any of the CSRF failures that are occurring on master.

**Comment by church29** [comment]
Where else are the csrf errors occuring? The only one I encountered was the system form.

**Comment by church29** [comment]
e.preventDefault()... should be fixed.

**Comment by drkitty** [comment]
Cool. I'll check it out.

**Comment by drkitty** [comment]
Please don't suppress *all* keypresses.

```diff
diff --git a/media/js/application.js b/media/js/application.js
index 167ad2f..9fb4f8c 100755
--- a/media/js/application.js
+++ b/media/js/application.js
@@ -32,8 +32,8 @@ function initForms() {
     });
     var keypressSelector = '#obj-form form :input:visible:not(textarea)';
     $(keypressSelector).on( 'keypress', function(e) {
-        e.preventDefault();
         if (e.keyCode == 13) {
+            e.preventDefault();
             $('.js-submit, .system-submit').focus().click();
         }
     });
```

**Comment by church29** [comment]
wow. Good call!

**Comment by drkitty** [comment]
Looks good.

**Pull request merged**
