### PR TITLE
Force hostnames lowercase

### PR DESCRIPTION
**Pull request by church29**
Resolves https://github.com/OSU-Net/cyder/issues/570

### CODE REVIEW

**Comment by drkitty** [comment]
Is this ready?

**Comment by murrown** [comment]
No, because although the domain name and the system name are forced to be lowercase, the front label is not... unless that was changed in a different pull request.

**Comment by drkitty** [comment]
So when that change is made the pull request will be ready?

**Comment by murrown** [comment]
As far as I can tell, yeah. The label cleaning should probably occur in CydnsRecord or LabelDomainMixin or some other centralized location, so that all fqdns are forced to lowercase.

**Comment by drkitty** [comment]
`LabelDomainUtilsMixin` sounds like the best place to me. It already has a `clean` method and it's inherited from by every model with a `label` field.

**Comment by murrown** [comment]
The specs changed... we now want to retain case (as ugly as it is)

**Pull request closed without merging**
