### PR TITLE
Remove interface ctnrs, show all ctnr fields

### PR DESCRIPTION
**Pull request by murrown**
Supersedes https://github.com/OSU-Net/cyder/pull/973, resolves https://github.com/OSU-Net/cyder/issues/924, https://github.com/OSU-Net/cyder/issues/877
*Requires a schema migration.*

### CODE REVIEW

**Comment by murrown** [comment]
This allows users to change the containers on Systems, but it doesn't look like there's any sort of validation in place to ensure that the system's container is the same as the interface's domain's container.

**Comment by murrown** [comment]
And possibly, we might want to match containers of systems to dynamic interface's range's container. I guess I'll continue working on this tomorrow.

**Comment by murrown** [comment]
Alright, that should do it.

**Comment by akeym** [comment]
This seems ok except for the fact that we have #982 to deal with.  Don't merge this until that is fixed.

**Comment by akeym** [comment]
hmm. tests unhappy

**Comment by murrown** [comment]
:(

**Pull request merged**
