### PR TITLE
Make database things more reasonable

### PR DESCRIPTION
**Pull request by drkitty**
- Remove Celery. I don't recall the reason, but there's no point in reverting the change now.
- Set charsets and collations to the proper values.
- Squash South migrations.
- Move some database configuration into `settings` that was previously hardcoded.

There appears to be no difference in the migrated data between this branch and master. This branch 
has more to do with correctness and reproducible Cyder installations.

### CODE REVIEW

**Comment by drkitty** [comment]
MySQL doesn't support keys longer than 767 bytes. For various reasons, this means that using the `utf8mb4` charset would require reimplementing a significant part of Django's test framework. This would be very difficult. Unless we can substitute PostgreSQL for MySQL, we may have to settle for using the `utf8` charset and manually disallowing 4-byte code points.

**Comment by murrown** [comment]
There's no reason why we would need to support the full `utf8mb4` charset, but I'm not sure what you mean by "disallow" it. I thought that the whole issue was that MySQL is weird about it, otherwise we would have already disabled it.

**Comment by drkitty** [comment]
Sorry for the poor wording. We need to provide a friendly error message if the user inputs a code point greater than U+FFFF. If we don't, the user will just get a cryptic database error.

**Comment by drkitty** [comment]
**Partially superseded by PR #814.**

**Pull request closed without merging**
